_security_logout:
    resource: security.route_loader.logout
    type: service

    # role_hierarchy:
    #     ROLE_ADMIN: ROLE_USER
    #     ROLE_MANAGER: ROLE_USER

    #  access_control:
    #     - { path: ^/admin, roles: ROLE_ADMIN }
    #     - { path: ^/technical, roles: ROLE_TECHNICAL }
    #     - { path: ^/, roles: PUBLIC_ACCESS }
